version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "kedric"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "kedric"
    ignore:
      # For deps, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
